apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-control-plane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: oda-canvas
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: 1.24.0
    helm:
      values: |
        pilot:
          autoscaleEnabled: true
          autoscaleMin: 2
          autoscaleMax: 5
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          env:
            PILOT_ENABLE_WORKLOAD_ENTRY_AUTOREGISTRATION: true
            PILOT_ENABLE_CROSS_CLUSTER_WORKLOAD_ENTRY: true
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2


